### ISSUE TITLE
[Story] Timeline activity detail view

### ISSUE THREAD

**Issue by ppeelen** [SwiftIsland/island-app#26]
**User story**
As a user I would like to open an activity from the timeline to read more details. If an activity has a mentor attached to it, I would like to be able to view the mentor details.

**Details**
Currently the timeline shows the full description of the activity. The timeline should show only the first 3 lines of the description. When the user taps the activity (didSelectRow), the view should push to the details of said activity.

**Comment by SpacyRicochet** [comment]
This looks like a fun one for me. I can pick this up :)

**Comment by funky-monkey** [comment]
@SpacyRicochet awesome! Go for it!
