### ISSUE TITLE
[Story] Show user location on map

### ISSUE THREAD

**Issue by ppeelen** [SwiftIsland/island-app#27]
**User Story**
As a user I would like to know where I am located on the map contra the bungalows. If I am somewhere on the island Texel I would like the map to initially zoom to show my location as well as the location of the bungalows; however if I am further away then I would like the map to act as it currently does.

**Technical details**
Currently there was no time to implement the current location support in the app. This should be added.

**Comment by i5glu** [comment]
Hello, I've checked existing code and I would like to work on this as part of Hacktoberfest :)

**Comment by ppeelen** [comment]
@iglushchuk go ahead =) When you have something you like to contribute, please make a pull request.

**Comment by break2k** [comment]
Hey guys, 

feel free to close this PR so people like me who are watching to contribute for Hacktoberfest do not do this accidentally by overlooking #60 

Will grab one of the other issues if this is fine with you.
