### ISSUE TITLE
[Bug] The titles for bungalow names are off by a few pixels

### ISSUE THREAD

**Issue by ppeelen** [SwiftIsland/island-app#28]
**Describe the bug**
Currently the titles of the bungalows are off by a few pixels. They should be centered on the bungalows.

**To Reproduce**
1. Go to Map
2. Zoom to show bungalows

**Expected behaviour**
Titles are in the middle of the bungalow.

**Screenshots**
![IMG_1277](https://user-images.githubusercontent.com/1107400/59999535-82fb9d00-9662-11e9-9adc-63acef842417.PNG)

**Comment by SpacyRicochet** [comment]
We can probably close this issue if the PR fixes it? @ppeelen @funky-monkey
