### ISSUE TITLE
Mentor card view on iPhone 5s too high

### ISSUE THREAD

**Issue by SpacyRicochet** [SwiftIsland/island-app#36]
**Describe the bug**
The mentor card view on iPhone 5s is too high, cutting off part of the Mentor photo.

**To Reproduce**
1. Go to 'Mentor'
2. Click on 'a mentor'
3. See Mentor card view

**Expected behavior**
The mentor card view is somewhat lower and the photo is not cut off.

**Screenshots**
![Simulator Screen Shot - iPhone 5s - 2019-06-25 at 10 55 09](https://user-images.githubusercontent.com/904596/60086454-5ff0ec00-973b-11e9-9056-d4783bfe58b1.png)

**Desktop (please complete the following information):**
 - iOS 12.2
 - iPhone 5s simulator 

**Additional information:**

Related, you can't actually tap 'outside' of the card view; probably because that is part of the actual view controller and not of the tap gesture on the visual effect. This is somewhat annoying on iPhone 5s because it only allows you to dismiss the view by dragging the handle.

**Comment by ppeelen** [comment]
Nice find! Definitely something we need to fix
