### ISSUE TITLE
Improved support Dynamic Type in the Mentor detail screen

### ISSUE THREAD

**Issue by SpacyRicochet** [SwiftIsland/island-app#37]
**Is your feature request related to a problem? Please describe.**
The mentor detail screen (in the card view) does not support Dynamic Type properly. To achieve this, the following should be done;

![Simulator Screen Shot - iPhone 5s - 2019-06-25 at 10 55 09](https://user-images.githubusercontent.com/904596/60086878-2f5d8200-973c-11e9-89f1-192314f9241e.png)

* [ ] Make the name label conform to dynamic type and allow to adjust on trait changes.
  * Take care to avoid the title label going over or under the photo. This may require a small design change (or a larger code change to cut out the photo from the text rendering.)
* [ ] Make the story label conform to dynamic type and allow to adjust on trait changes.
* [ ] Consider making the icons adjust according to text styles.
* [ ] Note that the screen should be scrollable to accomodate AXXXL text.

**Comment by subdan** [comment]
Hello. I would like to fix this issue as part of Hacktoberfest. I will open Pull Request on October 1.

**Comment by funky-monkey** [comment]
Hi @subdan that sound good!

There are some issues with the PR - If these are fixed, I'll merge your PR.

Best, 
Sidney

**Comment by subdan** [comment]
Ok. I'll fix these issues.
