### ISSUE TITLE
[Story] Dark Mode

### ISSUE THREAD

**Issue by SpacyRicochet** [SwiftIsland/island-app#62]
**User Story**
As a user I would like to use the app in Dark Mode without it looking weird 😬 

**Context**
![IMG_FF4BB39EA6A3-1](https://user-images.githubusercontent.com/904596/66309681-83b2f900-e90a-11e9-9188-4fa1d4bd07a7.jpeg)
![IMG_BBF62F1E96B6-1](https://user-images.githubusercontent.com/904596/66311686-4bfa8000-e90f-11e9-88e6-515c61381509.jpeg)
![IMG_6EDD70122627-1](https://user-images.githubusercontent.com/904596/66311687-4e5cda00-e90f-11e9-927a-02c54f94793b.jpeg)

**Comment by zappycode** [comment]
Hey I'm doing Hacktoberfest and I'll like to do this. I actually just finished adding dark mode to one of my apps

**Comment by funky-monkey** [comment]
Hi @zappycode, 

Sounds good, go for it!

Cheers, 
Sidney

**Comment by zappycode** [comment]
Awesome!

**Comment by BasThomas** [comment]
Closing as this has been resolved by #63 :)
